name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-github-pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/hn-app/package-lock.json

    - name: Install dependencies
      run: |
        cd frontend/hn-app
        npm ci

    - name: Build Angular app for production (SPA)
      run: |
        cd frontend/hn-app
        npm run build -- --configuration=spa --base-href="/hacker-news-viewer/"

    - name: Setup Pages
      uses: actions/configure-pages@v4
      with:
        enablement: true

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: frontend/hn-app/dist/hn-app/browser

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
